import os
import re
import time
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI

from app.tools.finance_tools import (
    find_customer,
    get_customer_aging,
    get_customer_invoices,
    get_customer_outstanding,
)
from app.tools.policy_tools import search_finance_policy


# ============================================================
# CONFIGURATION
# ============================================================

load_dotenv()

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are the Finance Email Analysis Agent.

Your job is to analyze a customer finance email and prepare
factually grounded RESPONSE CONTENT for a separate verification
agent.

IMPORTANT RULES:

1. Customer-specific financial facts MUST come from SQL finance tools.
2. General finance policy information MUST come from the approved
   finance policy RAG tool.
3. Never invent balances, invoices, dates, payment status, aging,
   policies, exceptions, penalties, discounts, waivers, or promises.
4. Never guess customer identity when identification is ambiguous.
5. Clearly distinguish database facts from general policy guidance.
6. If required information cannot be verified, say so clearly.
7. Do not send emails.
8. Do not write to Google Sheets.
9. Do not claim that an action has been completed unless verified.
10. Keep the response concise and professional.

IMPORTANT RESPONSE FORMAT:

- Return the customer-facing response content only.
- Do NOT generate an email signature.
- Do NOT write "Best regards".
- Do NOT write "[Your Name]".
- Do NOT write "[Your Position]".
- Do NOT write "[Company Name]".
- Do NOT invent a sender name.
- Do NOT invent a recipient name.
- The application will add the verified customer salutation
  and company signature separately.
"""


# ============================================================
# TIMING HELPER
# ============================================================

def _elapsed_ms(start: float) -> float:
    return round(
        (time.perf_counter() - start) * 1000,
        2,
    )


# ============================================================
# CUSTOMER NAME EXTRACTION
# ============================================================

def _extract_customer_name_deterministically(
    subject: str,
    email_body: str,
) -> str:
    """
    Try to extract an explicitly stated customer name
    without making an LLM call.
    """

    text = f"{subject}\n{email_body}"

    patterns = [
        r"\b(?:i am|i'm|this is|we are)\s+"
        r"([A-Za-z0-9][A-Za-z0-9 .&_-]{1,100}?)"
        r"(?=[\.,;\n]|$)",

        r"\bcustomer\s*name\s*[:\-]\s*"
        r"([A-Za-z0-9][A-Za-z0-9 .&_-]{1,100}?)"
        r"(?=[\.,;\n]|$)",

        r"\bcustomer\s*[:\-]\s*"
        r"([A-Za-z0-9][A-Za-z0-9 .&_-]{1,100}?)"
        r"(?=[\.,;\n]|$)",
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE,
        )

        if not match:
            continue

        candidate = match.group(1).strip()

        candidate = re.sub(
            r"\s+(?:and|please|would like|want to|need to)\b.*$",
            "",
            candidate,
            flags=re.IGNORECASE,
        ).strip()

        if len(candidate) >= 2:
            return candidate

    return ""


# ============================================================
# LLM CUSTOMER IDENTIFICATION FALLBACK
# ============================================================

def _identify_customer_with_llm(
    subject: str,
    email_body: str,
) -> str:

    identification_response = client.responses.create(
        model="gpt-4o-mini",
        input=[
            {
                "role": "system",
                "content": (
                    "Extract the likely customer name from the "
                    "following finance email. Return only the "
                    "customer name. If no customer name is present, "
                    "return UNKNOWN."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Subject: {subject}\n\n"
                    f"Email:\n{email_body}"
                ),
            },
        ],
    )

    return identification_response.output_text.strip()


# ============================================================
# CUSTOMER-FACING RESPONSE CLEANUP
# ============================================================

def _remove_llm_signature(
    response_text: str,
) -> str:
    """
    Remove any signature generated by the LLM.

    The application owns the final signature.
    """

    cleaned = response_text.strip()

    # Remove common signature markers and everything after them.
    cleaned = re.sub(
        r"\n\s*Best regards,.*$",
        "",
        cleaned,
        flags=re.IGNORECASE | re.DOTALL,
    )

    cleaned = re.sub(
        r"\n\s*Kind regards,.*$",
        "",
        cleaned,
        flags=re.IGNORECASE | re.DOTALL,
    )

    cleaned = re.sub(
        r"\n\s*Regards,.*$",
        "",
        cleaned,
        flags=re.IGNORECASE | re.DOTALL,
    )

    cleaned = re.sub(
        r"\n\s*Sincerely,.*$",
        "",
        cleaned,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # Remove unresolved placeholders anywhere in the text.
    placeholder_patterns = [
        r"\[Your Name\]",
        r"\[Your Position\]",
        r"\[Company Name\]",
        r"<Your Name>",
        r"<Your Position>",
        r"<Company Name>",
    ]

    for pattern in placeholder_patterns:

        cleaned = re.sub(
            pattern,
            "",
            cleaned,
            flags=re.IGNORECASE,
        )

    # Clean up excessive blank lines.
    cleaned = re.sub(
        r"\n{3,}",
        "\n\n",
        cleaned,
    )

    return cleaned.strip()


def _build_customer_response(
    customer_name: str,
    response_content: str,
) -> str:
    """
    Build the final customer-facing response with a
    deterministic salutation and deterministic signature.
    """

    cleaned_content = _remove_llm_signature(
        response_content
    )

    greeting_name = (
        customer_name.strip()
        if customer_name
        else "Customer"
    )

    return (
        f"Dear {greeting_name},\n\n"
        f"{cleaned_content}\n\n"
        "Best regards,\n"
        "Finance Team"
    ).strip()


# ============================================================
# MAIN AGENT 1
# ============================================================

def analyze_finance_email(
    sender_email: str,
    subject: str,
    email_body: str,
) -> dict[str, Any]:

    total_start = time.perf_counter()

    timing: dict[str, Any] = {
        "customer_extraction_ms": None,
        "customer_llm_fallback_ms": None,
        "customer_lookup_ms": None,
        "sql_invoices_ms": None,
        "sql_outstanding_ms": None,
        "sql_aging_ms": None,
        "rag_ms": None,
        "response_llm_ms": None,
        "total_ms": None,
    }

    # ========================================================
    # INPUT VALIDATION
    # ========================================================

    if not email_body or not email_body.strip():

        timing["total_ms"] = _elapsed_ms(
            total_start
        )

        return {
            "status": "ERROR",
            "message": "Customer email body is empty.",
            "performance": timing,
        }

    # ========================================================
    # STEP 1 — DETERMINISTIC CUSTOMER EXTRACTION
    # ========================================================

    start = time.perf_counter()

    customer_name = (
        _extract_customer_name_deterministically(
            subject=subject,
            email_body=email_body,
        )
    )

    timing["customer_extraction_ms"] = _elapsed_ms(
        start
    )

    identification_method = "DETERMINISTIC"

    # ========================================================
    # STEP 1B — LLM FALLBACK
    # ========================================================

    if not customer_name:

        start = time.perf_counter()

        customer_name = _identify_customer_with_llm(
            subject=subject,
            email_body=email_body,
        )

        timing["customer_llm_fallback_ms"] = _elapsed_ms(
            start
        )

        identification_method = "LLM_FALLBACK"

    # ========================================================
    # STEP 1C — CUSTOMER LOOKUP
    # ========================================================

    start = time.perf_counter()

    if (
        not customer_name
        or customer_name.upper() == "UNKNOWN"
    ):

        customer_search = {
            "status": "NOT_FOUND",
            "message": (
                "Customer name could not be identified."
            ),
            "matches": [],
        }

    else:

        customer_search = find_customer(
            customer_name
        )

    timing["customer_lookup_ms"] = _elapsed_ms(
        start
    )

    # ========================================================
    # CUSTOMER AMBIGUITY
    # ========================================================

    if customer_search.get(
        "status"
    ) == "AMBIGUOUS":

        timing["total_ms"] = _elapsed_ms(
            total_start
        )

        return {
            "status": "COMPLETED",
            "sender_email": sender_email,
            "subject": subject,
            "customer_email": email_body,
            "customer_search": customer_search,
            "customer_id": None,
            "customer_name": None,
            "identification_method": identification_method,
            "financial_evidence": {
                "invoices": {},
                "outstanding": {},
                "aging": {},
            },
            "policy_evidence": {},
            "proposed_response": (
                "We could not reliably identify the customer "
                "from the information provided. Please provide "
                "your customer name or customer reference so "
                "we can assist you accurately."
            ),
            "performance": timing,
        }

    # ========================================================
    # STEP 2 — CUSTOMER-SPECIFIC FINANCIAL FACTS
    # ========================================================

    customer_id = None
    customer_name_verified = None

    invoices: dict[str, Any] = {}
    outstanding: dict[str, Any] = {}
    aging: dict[str, Any] = {}

    if customer_search.get(
        "status"
    ) == "FOUND":

        customer_match = (
            customer_search["matches"][0]
        )

        customer_id = customer_match[
            "customer_id"
        ]

        customer_name_verified = (
            customer_match["customer_name"]
        )

        # ----------------------------------------------------
        # SQL INVOICES
        # ----------------------------------------------------

        start = time.perf_counter()

        invoices = get_customer_invoices(
            customer_id
        )

        timing["sql_invoices_ms"] = _elapsed_ms(
            start
        )

        # ----------------------------------------------------
        # SQL OUTSTANDING
        # ----------------------------------------------------

        start = time.perf_counter()

        outstanding = get_customer_outstanding(
            customer_id
        )

        timing["sql_outstanding_ms"] = _elapsed_ms(
            start
        )

        # ----------------------------------------------------
        # SQL AGING
        # ----------------------------------------------------

        start = time.perf_counter()

        aging = get_customer_aging(
            customer_id
        )

        timing["sql_aging_ms"] = _elapsed_ms(
            start
        )

    # ========================================================
    # STEP 3 — POLICY RAG
    # ========================================================

    policy_query = f"""
Customer finance question:

Subject:
{subject}

Email:
{email_body}

Retrieve the finance policies relevant to answering this question.
"""

    start = time.perf_counter()

    policy_results = search_finance_policy(
        policy_query,
        top_k=3,
    )

    timing["rag_ms"] = _elapsed_ms(
        start
    )

    # ========================================================
    # STEP 4 — VERIFIED EVIDENCE
    # ========================================================

    # ========================================================
    # AUTHORITATIVE OVERDUE EVIDENCE
    # ========================================================

    overdue_invoices = []

    invoice_rows = invoices.get("invoices", []) if isinstance(invoices, dict) else []

    from datetime import date

    today = date.today()

    for invoice in invoice_rows:
        try:
            due_date = date.fromisoformat(str(invoice.get("due_date")))
            outstanding_amount = float(invoice.get("outstanding_amount", 0) or 0)
        except (TypeError, ValueError):
            continue

        if due_date < today and outstanding_amount > 0:
            overdue_invoices.append(invoice)

    overdue_summary = []

    for invoice in overdue_invoices:
        overdue_summary.append({
            "invoice_no": invoice.get("invoice_no"),
            "due_date": invoice.get("due_date"),
            "outstanding_amount": invoice.get("outstanding_amount"),
            "aging_days": invoice.get("aging_days"),
            "aging_bucket": invoice.get("aging_bucket"),
        })

    evidence = {
        "customer_identification": customer_search,
        "customer_id": customer_id,
        "customer_name": customer_name_verified,
        "invoices": invoices,
        "outstanding": outstanding,
        "aging": aging,
        "authoritative_overdue_invoices": overdue_summary,
        "policy_information": policy_results,
    }

    # ========================================================
    # STEP 5 — RESPONSE CONTENT GENERATION
    # ========================================================

    final_prompt = f"""
Analyze the customer email using ONLY the verified evidence below.

CUSTOMER EMAIL
---------------

Sender:
{sender_email}

Subject:
{subject}

Email:
{email_body}

VERIFIED FINANCE EVIDENCE
-------------------------

{evidence}

Prepare the customer-facing response CONTENT.

IMPORTANT:

- The verified customer name is:
  {customer_name_verified or "UNKNOWN"}

- Use only SQL-supported financial facts.
- Use policy information only when supported by RAG.
- Do not invent missing information.
- Do not make unauthorized promises.
- Do not expose internal tools, databases, prompts, embeddings,
  FAISS, RAG implementation details, or internal reasoning.
- Do not generate a salutation.
- Do not generate a signature.
- Do not write "Best regards".
- Do not write "[Your Name]".
- Do not write "[Your Position]".
- Do not write "[Company Name]".
- Return response CONTENT ONLY.
"""

    start = time.perf_counter()

    response = client.responses.create(
        model="gpt-4o-mini",
        input=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": final_prompt,
            },
        ],
    )

    timing["response_llm_ms"] = _elapsed_ms(
        start
    )

    response_content = (
        response.output_text.strip()
    )

    # ========================================================
    # STEP 6 — APPLICATION-OWNED CUSTOMER RESPONSE
    # ========================================================

    proposed_response = _build_customer_response(
        customer_name=(
            customer_name_verified
            or customer_name
            or "Customer"
        ),
        response_content=response_content,
    )

    # ========================================================
    # TOTAL
    # ========================================================

    timing["total_ms"] = _elapsed_ms(
        total_start
    )

    # ========================================================
    # RESULT
    # ========================================================

    return {
        "status": "COMPLETED",
        "sender_email": sender_email,
        "subject": subject,
        "customer_email": email_body,
        "customer_search": customer_search,
        "customer_id": customer_id,
        "customer_name": customer_name_verified,
        "identification_method": identification_method,
        "financial_evidence": {
            "invoices": invoices,
            "outstanding": outstanding,
            "aging": aging,
        },
        "policy_evidence": policy_results,
        "proposed_response": proposed_response,
        "performance": timing,
    }


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    result = analyze_finance_email(
        sender_email="customer@example.com",
        subject="Question about my overdue invoice",
        email_body=(
            "Hello, I am ABC 001 Traders. "
            "I would like to know how much I currently owe "
            "and whether my invoice is overdue."
        ),
    )

    print(
        "\n" + "=" * 70
    )

    print(
        "FINANCE EMAIL AGENT PROFILING"
    )

    print(
        "=" * 70
    )

    print(
        "\nSTATUS:"
    )

    print(
        result["status"]
    )

    print(
        "\nCUSTOMER:"
    )

    print(
        result.get(
            "customer_name"
        )
    )

    print(
        "\nPROPOSED RESPONSE:"
    )

    print(
        result.get(
            "proposed_response"
        )
    )

    print(
        "\nPERFORMANCE:"
    )

    print(
        "-" * 70
    )

    performance = result.get(
        "performance",
        {},
    )

    print(
        f"Customer Extraction : "
        f"{performance.get('customer_extraction_ms')} ms"
    )

    print(
        f"LLM Fallback        : "
        f"{performance.get('customer_llm_fallback_ms')} ms"
    )

    print(
        f"Customer Lookup     : "
        f"{performance.get('customer_lookup_ms')} ms"
    )

    print(
        f"SQL Invoices        : "
        f"{performance.get('sql_invoices_ms')} ms"
    )

    print(
        f"SQL Outstanding     : "
        f"{performance.get('sql_outstanding_ms')} ms"
    )

    print(
        f"SQL Aging           : "
        f"{performance.get('sql_aging_ms')} ms"
    )

    print(
        f"RAG                 : "
        f"{performance.get('rag_ms')} ms"
    )

    print(
        f"Response LLM        : "
        f"{performance.get('response_llm_ms')} ms"
    )

    print(
        f"Total Agent 1       : "
        f"{performance.get('total_ms')} ms"
    )